/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.polylib.ui;

import com.mycompany.polylib.utils.MsgBox;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author ngocquy
 */
public class QuenMatKhauJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgetLoginJFrame
     */
    public QuenMatKhauJFrame() {
        initComponents();
        txt_email.setBackground(new java.awt.Color(0, 0, 0, 1));
        txt_MatKhauMoi.setBackground(new java.awt.Color(0, 0, 0, 1));
//        txt_MatKhauMoi.setEchoChar((char) 0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String password = null;

    QuenMatKhauJFrame(DangNhapJDialog aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_MatKhauMoi = new javax.swing.JPasswordField();
        btn_XacNhan = new javax.swing.JButton();
        btn_DangNhap = new javax.swing.JButton();
        btn_Gui = new javax.swing.JButton();
        btnHienThiMK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LOGIN.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quên Mật Khẩu?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 300, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, 20));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã xác nhận");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 20));

        txt_email.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 340, 40));

        txt_MatKhauMoi.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        txt_MatKhauMoi.setForeground(new java.awt.Color(255, 255, 255));
        txt_MatKhauMoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_MatKhauMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauMoiActionPerformed(evt);
            }
        });
        getContentPane().add(txt_MatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 340, 40));

        btn_XacNhan.setBackground(new java.awt.Color(0, 102, 255));
        btn_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_XacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btn_XacNhan.setText("Xác nhận");
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_XacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 260, 50));

        btn_DangNhap.setBackground(new java.awt.Color(0, 102, 255));
        btn_DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_DangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_DangNhap.setText("Đăng nhập");
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 240, 50));

        btn_Gui.setBackground(new java.awt.Color(0, 102, 255));
        btn_Gui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Gui.setForeground(new java.awt.Color(255, 255, 255));
        btn_Gui.setText("Gửi mail");
        btn_Gui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Gui, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, 30));

        btnHienThiMK.setBackground(new java.awt.Color(102, 102, 102));
        btnHienThiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye.png"))); // NOI18N
        btnHienThiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiMKActionPerformed(evt);
            }
        });
        getContentPane().add(btnHienThiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 810, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        kiemtra();
        System.out.println(txt_MatKhauMoi.getText());
        System.out.println(txt_MatKhauMoi.getText().length());
    }//GEN-LAST:event_btn_XacNhanActionPerformed

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        openDangNhap();
    }//GEN-LAST:event_btn_DangNhapActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_GuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuiActionPerformed
        password = generateRandomPassword(6);
        Subiject();
    }//GEN-LAST:event_btn_GuiActionPerformed

    private void txt_MatKhauMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatKhauMoiActionPerformed

    private void btnHienThiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiMKActionPerformed
        hienThiMK();
    }//GEN-LAST:event_btnHienThiMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhauJFrame().setVisible(true);
            }
        });
    }

    public void openDangNhap() {
        DangNhapJDialog dn = new DangNhapJDialog();
        dn.setVisible(true);
        QuenMatKhauJFrame.this.dispose();
    }

    int count = 0;

    public void hienThiMK() {
        if (count == 0) {
            txt_MatKhauMoi.setEchoChar((char) 0);
            System.out.println("Nút bấm đã được nhấp chuột");
            count = 1;
        } else if (count == 1) {
            txt_MatKhauMoi.setEchoChar('*');
            System.out.println(count);
            count = 0;
        }
    }

    public void Subiject() {
        Properties pro = new Properties();
        pro.put("mail.smtp.auth", true);
        pro.put("mail.smtp.starttls.enable", "true");
        pro.put("mail.smtp.host", "smtp.gmail.com");
        pro.put("mail.smtp.port", "587");
        pro.put("mail.smtp.socketFactory.port", "587");
        pro.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        pro.put("mail.smtp.ssl.protocols", "TLSv1.2");
        String Email = "quyphnpc08190@fpt.edu.vn";
        String Pass = "tzgbsqwxchyowmja";
        Session session = Session.getInstance(pro,
                new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(Email, Pass);
            }
        }
        );
        try {
            Message myMessage = new MimeMessage(session);
            myMessage.setFrom(new InternetAddress(Email));
            myMessage.setRecipients(Message.RecipientType.TO, InternetAddress.parse(txt_email.getText()));
            myMessage.setSubject("Cập nhật lại mật khẩu mới");
            myMessage.setContent(password, "text/html;charset=utf-8");
            Transport.send(myMessage);
            JOptionPane.showMessageDialog(this, "Mã xác nhận đã được gửi thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String generateRandomPassword(int length) {
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

        String randomString = "";
        Random random = new Random();

        for (int i = 0; i < 6; i++) {
            int index = random.nextInt(characters.length());
            randomString += characters.charAt(index);
        }

        System.out.println(randomString);
        System.out.println(randomString.length());
        return randomString;
    }

    void kiemtra() {
        if (txt_MatKhauMoi.getText().equalsIgnoreCase(password)) {
            MsgBox.alert(this, "đăng nhập thành công!");
        } else {
            MsgBox.alert(this, "đăng nhập thất bại!");
        }
    }

    void layMK() {
        password = generateRandomPassword(6); // Tạo mã xác nhận và cập nhật biến password
        txt_MatKhauMoi.setText(password); // Hiển thị mật khẩu mới trên giao diện (nếu cần)
        Subiject(); // Gửi mã xác nhận qua email
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiMK;
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JButton btn_Gui;
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txt_MatKhauMoi;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
